/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as SchoolIndexRouteImport } from './app/$school/index'
import { Route as SchoolYearRouteImport } from './app/$school/$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolIndexRoute = SchoolIndexRouteImport.update({
  id: '/$school/',
  path: '/$school/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolYearRoute = SchoolYearRouteImport.update({
  id: '/$school/$year',
  path: '/$school/$year',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$school/$year': typeof SchoolYearRoute
  '/$school': typeof SchoolIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$school/$year': typeof SchoolYearRoute
  '/$school': typeof SchoolIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$school/$year': typeof SchoolYearRoute
  '/$school/': typeof SchoolIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$school/$year' | '/$school'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$school/$year' | '/$school'
  id: '__root__' | '/' | '/$school/$year' | '/$school/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchoolYearRoute: typeof SchoolYearRoute
  SchoolIndexRoute: typeof SchoolIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$school/': {
      id: '/$school/'
      path: '/$school'
      fullPath: '/$school'
      preLoaderRoute: typeof SchoolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$school/$year': {
      id: '/$school/$year'
      path: '/$school/$year'
      fullPath: '/$school/$year'
      preLoaderRoute: typeof SchoolYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchoolYearRoute: SchoolYearRoute,
  SchoolIndexRoute: SchoolIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
