/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as TestRouteImport } from './app/test'
import { Route as SourceRouteImport } from './app/source'
import { Route as PrivacyRouteImport } from './app/privacy'
import { Route as IndexRouteImport } from './app/index'
import { Route as SchoolIndexRouteImport } from './app/$school/index'
import { Route as SchoolYearIndexRouteImport } from './app/$school/$year/index'
import { Route as SchoolYearIdIndexRouteImport } from './app/$school/$year/$id/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolIndexRoute = SchoolIndexRouteImport.update({
  id: '/$school/',
  path: '/$school/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolYearIndexRoute = SchoolYearIndexRouteImport.update({
  id: '/$school/$year/',
  path: '/$school/$year/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolYearIdIndexRoute = SchoolYearIdIndexRouteImport.update({
  id: '/$school/$year/$id/',
  path: '/$school/$year/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/source': typeof SourceRoute
  '/test': typeof TestRoute
  '/$school': typeof SchoolIndexRoute
  '/$school/$year': typeof SchoolYearIndexRoute
  '/$school/$year/$id': typeof SchoolYearIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/source': typeof SourceRoute
  '/test': typeof TestRoute
  '/$school': typeof SchoolIndexRoute
  '/$school/$year': typeof SchoolYearIndexRoute
  '/$school/$year/$id': typeof SchoolYearIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/source': typeof SourceRoute
  '/test': typeof TestRoute
  '/$school/': typeof SchoolIndexRoute
  '/$school/$year/': typeof SchoolYearIndexRoute
  '/$school/$year/$id/': typeof SchoolYearIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/source'
    | '/test'
    | '/$school'
    | '/$school/$year'
    | '/$school/$year/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/source'
    | '/test'
    | '/$school'
    | '/$school/$year'
    | '/$school/$year/$id'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/source'
    | '/test'
    | '/$school/'
    | '/$school/$year/'
    | '/$school/$year/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SourceRoute: typeof SourceRoute
  TestRoute: typeof TestRoute
  SchoolIndexRoute: typeof SchoolIndexRoute
  SchoolYearIndexRoute: typeof SchoolYearIndexRoute
  SchoolYearIdIndexRoute: typeof SchoolYearIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$school/': {
      id: '/$school/'
      path: '/$school'
      fullPath: '/$school'
      preLoaderRoute: typeof SchoolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$school/$year/': {
      id: '/$school/$year/'
      path: '/$school/$year'
      fullPath: '/$school/$year'
      preLoaderRoute: typeof SchoolYearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$school/$year/$id/': {
      id: '/$school/$year/$id/'
      path: '/$school/$year/$id'
      fullPath: '/$school/$year/$id'
      preLoaderRoute: typeof SchoolYearIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SourceRoute: SourceRoute,
  TestRoute: TestRoute,
  SchoolIndexRoute: SchoolIndexRoute,
  SchoolYearIndexRoute: SchoolYearIndexRoute,
  SchoolYearIdIndexRoute: SchoolYearIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
