/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as TestRouteImport } from './app/test'
import { Route as SourceRouteImport } from './app/source'
import { Route as PrivacyRouteImport } from './app/privacy'
import { Route as AboutRouteImport } from './app/about'
import { Route as HomeIndexRouteImport } from './app/_home/index'
import { Route as HomeSchoolIndexRouteImport } from './app/_home/$school/index'
import { Route as HomeSchoolYearIndexRouteImport } from './app/_home/$school/$year/index'
import { Route as HomeSchoolYearIdIndexRouteImport } from './app/_home/$school/$year/$id/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSchoolIndexRoute = HomeSchoolIndexRouteImport.update({
  id: '/_home/$school/',
  path: '/$school/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSchoolYearIndexRoute = HomeSchoolYearIndexRouteImport.update({
  id: '/_home/$school/$year/',
  path: '/$school/$year/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSchoolYearIdIndexRoute = HomeSchoolYearIdIndexRouteImport.update({
  id: '/_home/$school/$year/$id/',
  path: '/$school/$year/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/source': typeof SourceRoute
  '/test': typeof TestRoute
  '/': typeof HomeIndexRoute
  '/$school': typeof HomeSchoolIndexRoute
  '/$school/$year': typeof HomeSchoolYearIndexRoute
  '/$school/$year/$id': typeof HomeSchoolYearIdIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/source': typeof SourceRoute
  '/test': typeof TestRoute
  '/': typeof HomeIndexRoute
  '/$school': typeof HomeSchoolIndexRoute
  '/$school/$year': typeof HomeSchoolYearIndexRoute
  '/$school/$year/$id': typeof HomeSchoolYearIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/source': typeof SourceRoute
  '/test': typeof TestRoute
  '/_home/': typeof HomeIndexRoute
  '/_home/$school/': typeof HomeSchoolIndexRoute
  '/_home/$school/$year/': typeof HomeSchoolYearIndexRoute
  '/_home/$school/$year/$id/': typeof HomeSchoolYearIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/privacy'
    | '/source'
    | '/test'
    | '/'
    | '/$school'
    | '/$school/$year'
    | '/$school/$year/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/privacy'
    | '/source'
    | '/test'
    | '/'
    | '/$school'
    | '/$school/$year'
    | '/$school/$year/$id'
  id:
    | '__root__'
    | '/about'
    | '/privacy'
    | '/source'
    | '/test'
    | '/_home/'
    | '/_home/$school/'
    | '/_home/$school/$year/'
    | '/_home/$school/$year/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  SourceRoute: typeof SourceRoute
  TestRoute: typeof TestRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeSchoolIndexRoute: typeof HomeSchoolIndexRoute
  HomeSchoolYearIndexRoute: typeof HomeSchoolYearIndexRoute
  HomeSchoolYearIdIndexRoute: typeof HomeSchoolYearIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/$school/': {
      id: '/_home/$school/'
      path: '/$school'
      fullPath: '/$school'
      preLoaderRoute: typeof HomeSchoolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/$school/$year/': {
      id: '/_home/$school/$year/'
      path: '/$school/$year'
      fullPath: '/$school/$year'
      preLoaderRoute: typeof HomeSchoolYearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/$school/$year/$id/': {
      id: '/_home/$school/$year/$id/'
      path: '/$school/$year/$id'
      fullPath: '/$school/$year/$id'
      preLoaderRoute: typeof HomeSchoolYearIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  SourceRoute: SourceRoute,
  TestRoute: TestRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeSchoolIndexRoute: HomeSchoolIndexRoute,
  HomeSchoolYearIndexRoute: HomeSchoolYearIndexRoute,
  HomeSchoolYearIdIndexRoute: HomeSchoolYearIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
